# Generated by Django 2.0.6 on 2018-06-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data_hora',
            field=models.DateTimeField(),
        ),
    ]
