# Generated by Django 2.0.3 on 2018-06-30 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioDoacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('status', models.CharField(default='Iniciado', max_length=10)),
                ('id_mongo', models.CharField(blank=True, max_length=24, null=True)),
                ('escolhido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet')),
            ],
            options={
                'db_table': 'anuncio_doacao',
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('id_mongo', models.CharField(blank=True, max_length=24, null=True)),
                ('tipo', models.CharField(default='Obrigatório', max_length=11)),
                ('peso', models.IntegerField(null=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios_doacao.AnuncioDoacao')),
            ],
            options={
                'db_table': 'requisito',
            },
        ),
        migrations.AlterUniqueTogether(
            name='requisito',
            unique_together={('anuncio', 'titulo')},
        ),
    ]
