# Generated by Django 2.0.3 on 2018-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios_doacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciodoacao',
            name='id_mongo',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
