# Generated by Django 2.0.6 on 2018-06-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tem_midia',
        ),
        migrations.AddField(
            model_name='post',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Midia',
        ),
    ]
