# Generated by Django 2.0.6 on 2018-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180625_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='formato_arquivo',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
