# Generated by Django 2.0.6 on 2018-06-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_formato_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='formato_arquivo',
            field=models.CharField(blank=True, default='pic', max_length=3),
        ),
    ]
