# Generated by Django 2.0.6 on 2018-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180627_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='formato_arquivo',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.BooleanField(default=False, max_length=3),
        ),
    ]
