# Generated by Django 2.0.3 on 2018-06-16 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PF',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
                ('cpf', models.CharField(max_length=11)),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='PJ',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Usuario')),
                ('cnpj', models.CharField(max_length=14)),
            ],
            bases=('usuarios.usuario',),
        ),
    ]
