# Generated by Django 2.0.6 on 2018-06-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos_doacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processodoacao',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios_doacao.AnuncioDoacao'),
        ),
    ]
