# Generated by Django 2.0.6 on 2018-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='arquivo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
