# Generated by Django 2.0.6 on 2018-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_pet_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='binario',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='formato',
        ),
        migrations.AddField(
            model_name='foto',
            name='arquivo',
            field=models.FileField(default='placeholder.jpg', upload_to=''),
        ),
    ]
